; ---------------------------------------------------------------------------------
; 
; Delays that do NOT use any timer. Tuned for 16MHz Atmega 328p
;
; API
; Delay100ms       Delays for 100ms , pushes all registers, but flags might get changed
; Delay1s          Delays roughly for 1s
; Delay2ms
; Delay40us
; Delay450ns      ; very inaccurate
; Delay500ns      ; very inaccurate
; 
; ---------------------------------------------------------------------------------

